steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/malcomx2022/agribeningcp.git', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/agribenin/my-app', '.']
images:
- 'gcr.io/agribenin/my-app'
